format_version: 3
environments:
  generic:
    environment_variables:
      DOCKER_TAG: latest
      DOCKER_NO_CACHE: false
      DOCKER_BUILD_LOCAL: true
      #DOCKER_REG: docker.io
      #DOCKER_REGISTRY: docker.io
      #FROM_IMG_REGISTRY: docker.io
      #UCP_USER: test123
      #DOCKER_REGISTRY_INSECURE: true
    pipelines:
      - uplain-init
      - pip3-dev
      - cv-dev
      - cv-bazel-dev
pipelines:
  uplain-init:
    group: docker
    template: DockerBuild
    label_template: ${COUNT}
    lock_behavior: none
    environment_variables:
      DOCKER_FILE: bionic/Dockerfile
    materials:
      init-plain:
        git: https://github.com/qnib/init-plain.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: init-plain
      docker:
        git: https://github.com/qnib/uplain-init.git
        shallow_clone: false
        auto_update: true
        branch: master
        destination: docker
  pip3-dev:
    group: docker
    template: DockerBuild
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/qnib/uplain-pip3
        shallow_clone: false
        auto_update: true
        branch: master
        destination: docker
      uplain-init:
        pipeline: uplain-init
        stage: DockerBuild
        name: uplain-init
  cv-dev:
    group: docker
    template: DockerBuild
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/qnib/uplain-pip3-cv-dev
        shallow_clone: false
        auto_update: true
        branch: master
        destination: docker
      pip3-dev:
        pipeline: pip3-dev
        stage: DockerBuild
        name: pip3-dev
  cv-bazel-dev:
    group: docker
    template: DockerBuild
    label_template: ${COUNT}
    lock_behavior: none
    materials:
      git:
        git: https://github.com/qnib/uplain-bazel
        shallow_clone: false
        auto_update: true
        branch: master
        destination: docker
      cv-dev:
        pipeline: cv-dev
        stage: DockerBuild
        name: cv-dev
